version: "3.8"

services:
  client:
    container_name: quiz_party_frontend
    build:
      context: ./
      args:
        - EXPOSED_PORT=${FRONTEND_INTERNAL_HTTP_PORT}
    volumes:
      - .:/app
    ports:
      - "${FRONTEND_EXPOSED_HTTP_PORT}:${FRONTEND_INTERNAL_HTTP_PORT}"
